baseURL = "https://sebastiani-lengfurt.de"
languageCode = "de-de"
title = "Sebastiani Lengfurt"
theme = "sebastiani"

DefaultContentLanguage = "de"
SectionPagesMenu = "main"

[params]
body_classes = "avenir bg-white"
facebook = "https://www.facebook.com/SebastianiLengfurt"
github = "https://github.com/tfrdidi/sebastiani"
featured_image = "/images/start.jpg"



[[menu.main]]
    name = "Neuigkeiten"
    identifier = "Neuigkeiten"
    url = "/neuigkeiten/"
    weight = -100