baseURL = "https://hugo-testsite.netlify.com"
languageCode = "de-de"
title = "Sebastiani Lengfurt"
theme = "sebastiani"

DefaultContentLanguage = "de"
SectionPagesMenu = "main"

[params]
body_classes = "avenir bg-white"
facebook = "https://www.facebook.com/SebastianiLengfurt"
github = "https://github.com/tfrdidi/sebastiani"
featured_image = "/images/start.jpg"



