DefaultContentLanguage = "de"
SectionPagesMenu = "main"
baseURL = "https://sebastiani-lengfurt.de"
languageCode = "de-de"
theme = "sebastiani"
title = "Sebastiani Lengfurt"

[[menu.main]]
identifier = "Neuigkeiten"
name = "Neuigkeiten"
url = "/neuigkeiten/"
weight = 1

[[menu.main]]
identifier = "Bilder"
name = "Bilder"
url = "/bilder/"
weight = 2

[params]
body_classes = "avenir bg-white"
facebook = "https://www.facebook.com/SebastianiLengfurt"
featured_image = "/images/start.jpg"
github = "https://github.com/tfrdidi/sebastiani"

[privacy.youtube]
    disable = true
    privacyEnhanced = true
