baseURL = "http://hugo-testsite.netlify.com"
languageCode = "de-de"
title = "Sebastiani Lengfurt"
theme = "ananke"

DefaultContentLanguage = "de"
SectionPagesMenu = "main"

[params]
body_classes = "avenir bg-white"
facebook = "https://www.facebook.com/SebastianiLengfurt"
featured_image = "/images/start.jpg"



[[menu.test]]
name = "Home"
url  = "/"
weight = 0


[[menu.test]]
name = "Seiten"
url  = "sites/"
weight = 5

[[menu.test]]
name = "Blog"
url  = "post/"
weight = 10