---
new_page_extension: md
auto_deploy: false
admin_path: 
webhook_url: 
sections:
- path: content
  label: Pages
  create: all
- path: content/neuigkeiten
  label: Neuigkeiten
  create: all
- path: content/footer
  label: Footer
  create: all
upload_dir: static
public_path: "/uploads"
front_matter_path: ''
use_front_matter_path: false
file_template: ":year:/:month:/:day:/:filename:"
version: 0.37.1
